name = "Mock"
uuid = "7b8b9345-55cb-436a-a37e-3053b1f1c752"
version = "0.1.0"
authors = ["Yury Nuzhdin <nuzhdin.urii@gmail.com>"]

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
MacroTools = "0.5.16"
julia = "1.12 - 1.14"